Update mqtt script, more modern
It was failing to restart the service.

diff --git a/config/deploy/shared/mqtt_subscriber_init.sh.erb b/config/deploy/shared/mqtt_subscriber_init.sh.erb
--- a/config/deploy/shared/mqtt_subscriber_init.sh.erb
+++ b/config/deploy/shared/mqtt_subscriber_init.sh.erb
@@ -1,57 +1,105 @@
 #!/bin/sh
-
 ### BEGIN INIT INFO
-# Provides:          mqtt_subscriber
-# Required-Start:    $local_fs $remote_fs $network $syslog
-# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Provides:
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the mqtt_subscriber 
-# Description:       starts mqtt_subscriber
+# Short-Description: Start daemon at boot time
+# Description:       Enable service provided by daemon.
 ### END INIT INFO
 
 set -e
 
-# Feel free to change any of the following variables for your app:
-TIMEOUT=${TIMEOUT-60}
-APP_ROOT=<%= current_path %>
-PID_DIR=$APP_ROOT/tmp/pids
-PID=$PID_DIR/mqtt_subscriber.pid
-CMD="cd $APP_ROOT;  bundle exec rake mqtt:sub RAILS_ENV=<%= fetch(:rails_env)  %> > $APP_ROOT/log/mqtt_subscriber.log 2>&1 &"
-AS_USER=<%= fetch(:deploy_user) %>
-set -u
+dir=<%= current_path %>
+cmd="cd $dir;  bundle exec rake mqtt:sub RAILS_ENV=<%= fetch(:rails_env)  %> > $dir/log/mqtt_subscriber.log 2>&1 &"
+user=<%= fetch(:deploy_user) %>
 
-sig () {
-  test -s "$PID" && kill -$1 `cat $PID`
+name="mqtt_subscriber"
+pid_file="$dir/tmp/pids/$name.pid"
+stdout_log="$dir/log/$name.log"
+stderr_log="$dir/log/$name.err"
+
+get_pid() {
+    cat "$pid_file"
 }
 
-run () {
-  if [ "$(id -un)" = "$AS_USER" ]; then
-    eval $1
-  else
-    su -c "$1" - $AS_USER
-  fi
+is_running() {
+    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
 }
 
 case "$1" in
-start)
-  sig 0 && echo >&2 "Already running" && exit 0
-  run "$CMD"
-  ;;
-stop)
-  sig QUIT && exit 0
-  echo >&2 "Not running"
-  ;;
-force-stop)
-  sig TERM && exit 0
-  echo >&2 "Not running"
-  ;;
-restart|reload)
-  sig QUIT
-  run "$CMD"
-  ;;
-*)
-  echo >&2 "Usage: $0 <start|stop|restart|force-stop>"
-  exit 1
-  ;;
+    start)
+    if is_running; then
+        echo "Already started"
+    else
+        echo "Starting $name"
+        cd "$dir"
+        if [ -z "$user" ]; then
+            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        else
+            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        fi
+        echo $! > "$pid_file"
+        if ! is_running; then
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            exit 1
+        fi
+    fi
+    ;;
+    stop)
+    if is_running; then
+        echo -n "Stopping $name.."
+        kill `get_pid`
+        for i in 1 2 3 4 5 6 7 8 9 10
+        # for i in `seq 10`
+        do
+            if ! is_running; then
+                break
+            fi
+
+            echo -n "."
+            sleep 1
+        done
+        echo
+
+        if is_running; then
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            exit 1
+        else
+            echo "Stopped"
+            if [ -f "$pid_file" ]; then
+                echo 'Pid file exists, trying to remove..'
+                rm "$pid_file"
+                if [ -f "$pid_file" ]; then
+                    echo 'Pid file removed!'
+                fi
+            fi
+        fi
+    else
+        echo "Not running"
+    fi
+    ;;
+    restart)
+    $0 stop
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
+        exit 1
+    fi
+    $0 start
+    ;;
+    status)
+    if is_running; then
+        echo "Running, pid file: $(cat $pid_file)"
+    else
+        echo "Stopped"
+        exit 1
+    fi
+    ;;
+    *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
+    ;;
 esac
+
+exit 0
